Tentative fix for Lazy Eager Loading with uuids
goravel/framework pull request #226
Opened 2023-06-30 21:33 UTC by Marian0

Closes [# ](https://github.com/goravel/goravel/issues/205)

## 📑 Description
I found Lazy Eager Loading was not working when using UUID primary keys, after debugging I found this change solves the issue but not sure about the implications this may have or if there is any better workaround.

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

2023-07-01 01:23 UTC, hwbrzzl requested changes
Let's have more discussion here: https://github.com/goravel/goravel/issues/205

2023-07-02 01:38 UTC, hwbrzzl reviewed
Thanks, perfect! Could you please change the base branch to v.12.x? Then we can release v1.12.5 these two days.

2023-07-02 13:17 UTC, Marian0 commented
> Thanks, perfect! Could you please change the base branch to v.12.x? Then we can release v1.12.5 these two days.

Done.

2023-07-02 13:33 UTC, hwbrzzl approved these changes
Perfect!

2023-07-02 13:33 UTC, merged